// renderer/components/button.jsx
import styles from './button.module.css';
import { FontAwesomeIcon as Icon } from '@fortawesome/react-fontawesome';

export default function ({
    label = 'Button',
    variant = 'secondary',
    size = 'sm',
    iconLeft = null,
    iconRight = null,
    customClass = '',
    ...props
}) {
    return (
        <button className={`${styles.button} ${styles[`size-${size}`]} ${styles[`variant-${variant}`]} ${customClass}`} {...props}>
            {iconLeft && <Icon className={styles.icon} icon={iconLeft} />}
            {label}
            {iconRight && <Icon className={styles.icon} icon={iconRight} />}
        </button>
    );
};

// src/components/button.svelte
<script>
    import './button.css';

    import Icon from 'svelte-fa';

    export let label = 'Button';

    export let variant = 'secondary';
    export let size = 'sm';

    export let iconLeft = null;
    export let iconRight = null;

    export let customClass = '';
    export let onClick = () => {};
</script>

<button class={`button size-${size} variant-${variant} ${customClass}`} on:click={onClick}>
    {#if iconLeft}
        <Icon icon={iconLeft} />
    {/if}
    {label}
    {#if iconRight}
        <Icon icon={iconRight} />
    {/if}
</button>
