// src/components/input.svelte
<script lang='ts'>
    import './input.css';

    export let label: string = 'Input';
    export let placeholder: string = null;

    export let size: 'sm' | 'md' | 'lg' = 'sm';
    export let customClass: string = '';
</script>

<h3 class='input-label'>{label}</h3>
<input class={`input size-${size} ${customClass}`} placeholder={placeholder} />

// renderer/components/input.jsx
import styles from './input.module.css';

export default function ({
    label = 'Button',
    placeholder = null,
    customClass = '',
    ...props
}) {
    return (
        <>
            <h3 className={styles['input-label']}>{label}</h3>
            <input className={`${styles.input} ${customClass}`} placeholder={placeholder} {...props} />
        </>
    );
};
