// src/components/layout.svelte
<script>
    import './layout.css';
    import Sidebar from './sidebar.svelte';

    import Home from '../content/home.svelte';
    import Bots from '../content/bots.svelte';

    import { logsActive as _logsActive, content as _content } from '../stores';

    let logsActive;
    let content;
    
    _logsActive.subscribe((value) => logsActive = value);
    _content.subscribe((value) => content = value);
</script>

<main>
    <Sidebar />
    <div class={`right ${logsActive && 'logs-active'}`}>
        <div class='content container'>
            {#if content === 'home'}
                <Home />
            {:else if content === 'bots'}
                <Bots />
            {/if}
        </div>
        <div class='logs container'>
            <p>Logs</p>
        </div>
    </div>
</main>

// renderer/components/layout.jsx
import styles from './layout.module.css';
import Sidebar from './sidebar';

import Home from '../content/home';
import Bots from '../content/bots';

import { useState } from 'react';

export default function () {
    let [content, setContent] = useState('home');
    let [logsActive, setLogsActive] = useState(true);

    return (
        <main className={styles.main}>
            <Sidebar customClass={`${styles.sidebar} ${styles.container}`} setContent={setContent} logsActive={logsActive} setLogsActive={setLogsActive} />
            <div className={`${styles.right} ${logsActive && styles['logs-active']}`}>
                <div className={`${styles.content} ${styles.container}`}>
                    {content === 'home' ? <Home /> : <Bots customClass={styles.container} />}
                </div>
                <div className={`${styles.logs} ${styles.container}`}>
                    <p>Logs</p>
                </div>
            </div>
        </main>
    );
};
